// import './instance'
// import './lifecycle'
// import './data-binding'
// import './computed'
// import './directive'
// import './component/define'
import './component/extend'
// import './component/v-model'
// import './component/feartures'
// import './component/render'
